### ISSUE TITLE
Version on the General registry

### ISSUE THREAD

**Issue by scabux** [hsgg/TwoFAST.jl#5]
When downloaded through the [General](https://github.com/JuliaRegistries/General) registry, the compatibility with SpecialFunctions.jl version 2.x does not work. This package has to be updated in the General registry (I am not sure if only the owner of this package can do that).

Thank you for developing and maintaining this package!

**Comment by hsgg** [comment]
Sorry, was a busy week. Thanks for alerting me to this! I have pushed v0.1.5 that should get to the General registry in just a bit.
